#!/command/with-contenv bash

if [ "${PH_VERBOSE:-0}" -gt 0 ] ; then
    set -x ;
fi

[[ ! -d /var/cache/lighttpd/uploads ]] && mkdir -p /var/cache/lighttpd/uploads || true
chown -R www-data:www-data /var/cache/lighttpd /run/lighttpd
chmod -R 755 /var/cache/lighttpd /run/lighttpd

#create if missing.
[[ ! -d /var/log/lighttpd/ ]] && mkdir -p /var/log/lighttpd/ || true
#set proper rights to ensure files will be readable.
chmod 755 /var/log/lighttpd

if [[ 1 -eq ${WEBLOGS_STDOUT:-0} ]]; then
  #lighthttpd cannot use /dev/stdout https://redmine.lighttpd.net/issues/2731
  for fi in /var/log/lighttpd/access-pihole.log /var/log/lighttpd/error-pihole.log
  do
    if [[ ! -p ${fi} ]]; then
      rm -f ${fi}
      mkfifo -m 600 ${fi}
    fi
  done
  chown -R www-data:www-data /var/log/lighttpd
  service lighttpd-access-log start
  service lighttpd-error-log start
  sleep 2
else
  #remove fifo if exists
  [[ -p /var/log/lighttpd/access-pihole.log ]] && rm -Rf /var/log/lighttpd/access-pihole.log
  [[ -p  /var/log/lighttpd/error-pihole.log ]] && rm -Rf /var/log/lighttpd/error-pihole.log

  # install /dev/null log files to ensure they exist (create if non-existing, preserve if existing)
  [[ ! -f /var/log/lighttpd/access-pihole.log ]] && install /dev/null /var/log/lighttpd/access-pihole.log
  [[ ! -f  /var/log/lighttpd/error-pihole.log ]] && install /dev/null /var/log/lighttpd/error-pihole.log

  # Ensure that permissions are set so that lighttpd can write to the logs
  chown -R www-data:www-data /var/log/lighttpd /run/lighttpd/
  chmod 0644 /var/log/lighttpd/access-pihole.log /var/log/lighttpd/error-pihole.log
fi

lighttpd -D -f /etc/lighttpd/lighttpd.conf
