name: buildx
on:
  #schedule:
  #  - cron: '0 2 * * *'
  push:
    branches:
      - master
    paths-ignore:
      - '.github/**'
  pull_request:
  release:
    types: [ published ]
  workflow_dispatch:

env:
  aptCacher: ''
  IMAGE: pihole
  PIHOLE_DOCKER_TAG: latest
  NAME: edgd1er/pihole
  S6_OVERLAY_VERSION: 3.2.0.0
  DEBIAN_VERSION: bookworm-slim
  DOCKER_PUSH: false
  DOCKER_LOAD: true
  BUILD_NOCACHE: false

jobs:
  buildx:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout dev branch if we are building nightly
        if: github.event_name == 'schedule'
        uses: actions/checkout@v4
        with:
          ref: dev
      - name: set github ref
        run: |
          echo "GITHUB_REF=${{ github.ref }}" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest
          install: true
          use: true

      - name: Builder instance name
        run: echo ${{ steps.buildx.outputs.name }}

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Cache Docker layers
        uses: actions/cache@v4
        id: cache
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to Docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          images: |
            ${{ secrets.DOCKERHUB_USER }}/pihole
          flavor: |
            latest=${{ startsWith( env.GITHUB_REF, 'refs/heads/master')  && ( github.event_name != 'schedule' ) }}
          tags: |
            type=schedule,pattern=nightly
            type=ref,event=branch,enable=${{ github.event_name != 'schedule' }}
            type=ref,event=tag

      - name: Set env DOCKER_PUSH
        run: |
          # tag = latest / master pushing image with tags
          if [[ $BRANCH == 'master' || $GITHUB_EVENT_NAME == 'release' ]]; then
            echo "DOCKER_PUSH=true" >> "$GITHUB_ENV"
            echo "DOCKER_LOAD=false" >> "$GITHUB_ENV"
          fi
          # tag = branch name / not master, pushing image with tags
          if [[ $BRANCH != 'master'  ]]; then
            echo "DOCKER_PUSH=true" >> "$GITHUB_ENV"
            echo "DOCKER_LOAD=false" >> "$GITHUB_ENV"
          fi

      - name: Build and no push
        if: ${{ env.DOCKER_LOAD }}
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: src
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
          no-cache: ${{ env.BUILD_NOCACHE }}
          load: true
          build-args: |
            NAME=${{ secrets.DOCKERHUB_USER }}/${{ env.IMAGE }}
            PIHOLE_DOCKER_TAG=${{ steps.meta.outputs.tags }}
            S6_OVERLAY_VERSION=${{ env.S6_OVERLAY_VERSION }}
            MAINTAINER=${{ env.GITHUB_SHA }}
            DEBIAN_VERSION=${{ env.DEBIAN_VERSION }}
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}

      - name: Build multi platforms and push
        if: ${{ env.DOCKER_PUSH }}
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: src
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
          no-cache: ${{ env.BUILD_NOCACHE }}
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          push: true
          build-args: |
            NAME=${{ secrets.DOCKERHUB_USER }}/${{ env.IMAGE }}
            PIHOLE_DOCKER_TAG=${{ steps.meta.outputs.tags }}
            S6_OVERLAY_VERSION=${{ env.S6_OVERLAY_VERSION }}
            MAINTAINER=${{ env.GITHUB_SHA }}
            DEBIAN_VERSION=${{ env.DEBIAN_VERSION }}
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}
      - name: Inspect builder
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"

      - name: Inspect image
        run: |
          docker buildx imagetools inspect ${{ secrets.DOCKERHUB_USER }}/${{ env.IMAGE }}:${{steps.meta.outputs.version }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/${{ secrets.DOCKERHUB_USER }}/${{ env.IMAGE }}:${{ steps.meta.outputs.version }}'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'

      - # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache